# General information
cuda = True
sanity = False
load_model = False
# Data information
input_size = 1000
nclasses = 138
output_size = 138
# Training parameters

lr = 0.001
weight_decay = 0#0.0001
batch_size = 64
max_epoch = 30
patience = 3
hidden_size = 1024
CUDA = True
# Network parameters
dropout = 0
